name = "cloudflare-xpanel"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "vpn-xpanel-db"
database_id = "your-d1-database-id"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "vpn-xpanel-db-dev"
database_id = "your-d1-database-dev-id"